name: Build

on:
  merge_group:
  pull_request:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_regular:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install prerequisites
        run: sudo apt-get update && sudo apt-get install -y g++-13
      - name: Prepare environment
        run: |
          echo "CXX=g++-13" >> $GITHUB_ENV
          echo "CMake: $(cmake --version | head -n 1)"
          echo "CXX  : $CXX"
          echo "rustc: $(rustc --version)"
      - name: Build CMake Project
        uses: threeal/cmake-action@v2.1.0
        with:
          # https://github.com/corrosion-rs/corrosion/blob/master/cmake/FindRust.cmake
          options: |
            Rust_RESOLVE_RUSTUP_TOOLCHAINS=OFF

  build_nix_shell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build CMake Project
        run: nix develop -i --command bash -c "mkdir build && cd build && cmake .. -G Ninja && ninja"

  build_nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: nix build
        run: |
          export EXPECTED="Hello World! first=0, second=1"
          nix run . | grep -q -F "$EXPECTED"
